import { StyleSheet } from "react-native";
import { COLORS } from "../constants/colors";

const dash = StyleSheet.create({
  root: { flex: 1, backgroundColor: COLORS.grayBg },

  topbar: {
    height: 64,
    backgroundColor: COLORS.blue2,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  brandWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 0,
  },
  brandLogo: {
    width: 34,
    height: 34,
    borderRadius: 8,
    backgroundColor: "#fff",
  },
  brand: { color: "#fff", fontSize: 18, fontWeight: "900" },
  topActions: { flexDirection: "row", gap: 10 },
  topActionsMobile: { flexDirection: "row", gap: 8, flexWrap: "wrap", alignItems: "center", justifyContent: "flex-end", rowGap: 8 },
  topBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  topBtnText: { color: "#fff", fontWeight: "900" },

  body: { flex: 1, flexDirection: "row", minHeight: 0 },
  bodyMobile: { flexDirection: "column" },

  sidebar: {
    width: 270,
    backgroundColor: "#F7F8FC",
    borderRightWidth: 1,
    borderRightColor: COLORS.grayBorder,
    padding: 16,
  },
  sidebarMenu: {
    flex: 1,
  },
  profileBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 14,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: COLORS.grayBorder,
    borderRadius: 16,
    shadowColor: "#0A2E6D",
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  avatar: { width: 46, height: 46, borderRadius: 999, backgroundColor: "#E6ECF7" },
  avatarLogo: {
    width: 104,
    height: 58,
    borderRadius: 10,
    backgroundColor: "#fff",
  },
  profileName: { fontWeight: "900", color: COLORS.blue2, fontSize: 16 },
  profileRole: { marginTop: 4, fontWeight: "900", color: COLORS.text, fontSize: 15 },

  menuTitleWrap: {
    marginTop: 18,
    marginBottom: 12,
    marginHorizontal: -16,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: COLORS.blue2,
  },
  menuTitle: { color: "#fff", fontWeight: "900", fontSize: 15, letterSpacing: 0.4 },

  item: {
    paddingVertical: 6,
    paddingHorizontal: 6,
    borderRadius: 18,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#E7EDF8",
    backgroundColor: "rgba(255,255,255,0.76)",
  },
  itemActive: {
    backgroundColor: "#F0F5FF",
    borderColor: "#C8D8FF",
  },
  itemHighlightActive: {
    backgroundColor: COLORS.blue2,
    borderColor: "#0A2E6D",
    shadowColor: "#0A2E6D",
    shadowOpacity: 0.2,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  itemInner: {
    flexDirection: "row",
    alignItems: "center",
    minHeight: 52,
    gap: 12,
    paddingHorizontal: 8,
  },
  itemIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "#EEF3FF",
    alignItems: "center",
    justifyContent: "center",
  },
  itemIconWrapActive: { backgroundColor: "#DCE8FF" },
  itemIconWrapHighlight: { backgroundColor: "rgba(255,255,255,0.18)" },
  itemIcon: { fontSize: 18, color: COLORS.blue2 },
  itemIconActive: { color: COLORS.blue2 },
  itemIconHighlight: { color: "#fff" },
  itemText: { flex: 1, fontWeight: "900", color: COLORS.text, fontSize: 14 },
  itemTextHighlight: { color: "#fff" },
  itemArrow: { fontSize: 26, color: "#9FB4DD", fontWeight: "900" },
  itemArrowActive: { color: COLORS.blue2 },
  itemArrowHighlight: { color: "#fff" },

  content: { flex: 1, backgroundColor: COLORS.grayBg, minWidth: 0 },
  contentMobile: { width: "100%" },

  h1: { fontSize: 26, fontWeight: "900", color: COLORS.text },
  h2: { marginTop: 4, marginBottom: 14, color: COLORS.muted, fontWeight: "800" },

  panel: {
    backgroundColor: "#fff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.grayBorder,
    padding: 16,
    marginBottom: 14,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  panelTitle: { fontSize: 16, fontWeight: "900", color: COLORS.blue2, marginBottom: 12 },

  label: { fontSize: 13, fontWeight: "800", color: COLORS.text, marginBottom: 6 },
  input: {
    height: 44,
    borderWidth: 1,
    borderColor: COLORS.grayBorder,
    borderRadius: 12,
    paddingHorizontal: 12,
    justifyContent: "center",
    backgroundColor: "#fff",
  },

  grid2: { flexDirection: "row", gap: 12 },
  grid3: { flexDirection: "row", gap: 12 },
  grid5: { flexDirection: "row", gap: 10 },
  toggleRow: { flexDirection: "row", gap: 10, marginBottom: 12 },
  toggleBtn: {
    flex: 1,
    height: 40,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.grayBorder,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
  },
  toggleBtnActive: { backgroundColor: "#E8F0FF", borderColor: "#BFD4FF" },
  toggleText: { fontWeight: "900", color: COLORS.text },
  toggleTextActive: { color: COLORS.blue2 },

  smallBox: { flex: 1 },
  smallLabel: { fontSize: 12, fontWeight: "900", color: COLORS.text, marginBottom: 6 },
  smallInput: {
    height: 40,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.grayBorder,
    backgroundColor: "#fff",
    paddingHorizontal: 10,
    color: COLORS.text,
  },
  radioRow: { marginTop: 6, flexDirection: "row", alignItems: "center", gap: 6 },
  radioOuter: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: COLORS.grayBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  radioOuterActive: { borderColor: COLORS.blue2 },
  radioInner: { width: 8, height: 8, borderRadius: 4, backgroundColor: COLORS.blue2 },
  radioText: { fontSize: 11, color: COLORS.muted, fontWeight: "800" },

  totalRow: {
    marginTop: 14,
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: 10,
  },
  totalLabel: { fontWeight: "900", color: COLORS.muted },
  totalBox: {
    height: 40,
    width: 120,
    borderRadius: 12,
    backgroundColor: "#EEF3FF",
    borderWidth: 1,
    borderColor: "#D9E5FF",
    justifyContent: "center",
    alignItems: "center",
  },
  totalText: { fontWeight: "900", color: COLORS.text },

  saveBtn: {
    height: 48,
    borderRadius: 12,
    backgroundColor: COLORS.blue2,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 6,
  },
  saveText: { color: "#fff", fontWeight: "900", fontSize: 16 },
  saveMsg: { marginTop: 8, color: COLORS.muted, fontWeight: "800" },
  suggestBox: {
    marginTop: -4,
    marginBottom: 10,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: COLORS.grayBorder,
    borderRadius: 12,
    overflow: "hidden",
  },
  suggestItem: { paddingVertical: 8, paddingHorizontal: 12 },
  suggestText: { color: COLORS.text, fontWeight: "700" },

  calendarOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.35)",
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
  },
  calendarCard: {
    width: 360,
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: COLORS.grayBorder,
  },
  calendarHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  calendarTitle: { fontWeight: "900", color: COLORS.text },
  calendarNavBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.grayBorder,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F9FAFB",
  },
  calendarNavText: { fontWeight: "900", color: COLORS.text },
  calendarWeekRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  calendarWeekText: {
    width: 44,
    textAlign: "center",
    fontWeight: "900",
    color: COLORS.muted,
    fontSize: 12,
  },
  calendarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  calendarDay: {
    width: 44,
    height: 36,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 6,
  },
  calendarDaySelected: { backgroundColor: "#E8F0FF" },
  calendarDayText: { fontWeight: "700", color: COLORS.text },
  calendarDayTextSelected: { color: COLORS.blue2, fontWeight: "900" },
  calendarDayWeekend: { color: COLORS.muted },
  calendarCloseBtn: {
    marginTop: 8,
    height: 40,
    borderRadius: 10,
    backgroundColor: COLORS.blue2,
    alignItems: "center",
    justifyContent: "center",
  },
  calendarCloseText: { color: "#fff", fontWeight: "900" },

  docRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: COLORS.grayBorder,
  },
  docTitle: { fontWeight: "900", color: COLORS.text },
  docSub: { marginTop: 2, color: COLORS.muted, fontWeight: "700" },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "#EEF3FF",
    borderWidth: 1,
    borderColor: "#D9E5FF",
  },
  badgeText: { fontWeight: "900", color: COLORS.blue2, fontSize: 12 },
  docBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: COLORS.blue2,
  },
  docBtnText: { color: "#fff", fontWeight: "900" },
});

export default dash;

Object.assign(dash, {
  topbarMobile: {
    height: "auto",
    minHeight: 64,
    paddingVertical: 12,
    alignItems: "flex-start",
    gap: 10,
  },
  topbarRowMobile: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  drawerOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.28)",
    justifyContent: "flex-start",
    alignItems: "flex-start",
  },
  drawerPanel: {
    width: "84%",
    maxWidth: 320,
    height: "100%",
    backgroundColor: "#F7F8FC",
    borderRightWidth: 1,
    borderRightColor: COLORS.grayBorder,
    padding: 16,
  },
  drawerHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  drawerCloseBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: "rgba(22,63,138,0.08)",
  },
  drawerCloseText: {
    color: COLORS.blue2,
    fontWeight: "900",
  },
});



