import { StyleSheet } from "react-native";
import { COLORS } from "../constants/colors";

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: COLORS.grayBg,
    alignItems: "center",
    justifyContent: "center",
  },
  bgBase: { ...StyleSheet.absoluteFillObject, backgroundColor: COLORS.grayBg },

  semiCircleBlue: {
    position: "absolute",
    top: -260,
    left: -120,
    width: 700,
    height: 520,
    backgroundColor: COLORS.blue,
    borderRadius: 9999,
    zIndex: 0,
  },
  semiCircleOrange: {
    position: "absolute",
    top: -180,
    right: -180,
    width: 520,
    height: 420,
    backgroundColor: COLORS.orange,
    borderRadius: 9999,
    opacity: 0.18,
    zIndex: 0,
  },

  card: {
    width: "90%",
    maxWidth: 430,
    backgroundColor: COLORS.white,
    borderRadius: 18,
    padding: 22,
    borderWidth: 1,
    borderColor: COLORS.grayBorder,
    zIndex: 1,
    shadowColor: "#000",
    shadowOpacity: 0.14,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  logo: {
    width: "100%",
    height: 80,
    resizeMode: "contain",
    alignSelf: "center",
    marginBottom: 10,
  },
  title: {
    fontSize: 26,
    fontWeight: "800",
    color: COLORS.blue,
    marginBottom: 6,
    textAlign: "center",
  },
  subtitle: {
    fontSize: 14,
    color: COLORS.muted,
    marginBottom: 18,
    textAlign: "center",
  },
  label: {
    fontSize: 13,
    fontWeight: "700",
    color: COLORS.text,
    marginBottom: 6,
  },
  input: {
    height: 46,
    borderWidth: 1,
    borderColor: COLORS.grayBorder,
    borderRadius: 12,
    paddingHorizontal: 12,
    color: COLORS.text,
    backgroundColor: "#fff",
    marginBottom: 12,
  },
  button: {
    height: 48,
    borderRadius: 12,
    backgroundColor: COLORS.blue,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 6,
  },
  buttonText: { color: COLORS.white, fontWeight: "800", fontSize: 15 },
  linkBtn: { marginTop: 10, alignItems: "center" },
  linkBtnText: { color: COLORS.blue, fontWeight: "800" },
  resetBox: {
    marginTop: 12,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.grayBorder,
    backgroundColor: "#F8FAFF",
  },
  resetTitle: { fontWeight: "800", color: COLORS.text, marginBottom: 10 },
  secondaryBtn: {
    height: 40,
    borderRadius: 10,
    backgroundColor: "#EEF3FF",
    borderWidth: 1,
    borderColor: "#D9E5FF",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  secondaryBtnText: { color: COLORS.blue, fontWeight: "800" },
  resetMsg: { color: COLORS.muted, fontWeight: "700", marginTop: 6 },
  footer: {
    marginTop: 14,
    textAlign: "center",
    color: COLORS.muted,
    fontSize: 12,
    fontWeight: "700",
  },
});

export default styles;
