import { StyleSheet } from "react-native";
import { COLORS } from "../constants/colors";

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: COLORS.bg,
    alignItems: "center",
    justifyContent: "center",
  },
  bgBase: { ...StyleSheet.absoluteFillObject, backgroundColor: COLORS.bg },

  // Fondos decorativos
  topLeftBlue: {
    position: "absolute",
    top: -220,
    left: -220,
    width: 520,
    height: 520,
    borderRadius: 9999,
    backgroundColor: COLORS.blue,
  },
  topLeftBlueSoft: {
    position: "absolute",
    top: -110,
    left: -40,
    width: 400,
    height: 400,
    borderRadius: 9999,
    backgroundColor: "#7DA7E0",
    opacity: 0.6,
  },
  topLeftOrange: {
    position: "absolute",
    top: -30,
    left: -5,
    width: 230,
    height: 230,
    borderRadius: 9999,
    backgroundColor: COLORS.orange,
    opacity: 0.95,
  },
  topRightOrange: {
    position: "absolute",
    top: -120,
    right: -120,
    width: 300,
    height: 300,
    borderRadius: 9999,
    backgroundColor: COLORS.orange,
    opacity: 0.2,
  },
  dotOrange: {
    position: "absolute",
    top: 120,
    right: 150,
    width: 12,
    height: 12,
    borderRadius: 999,
    backgroundColor: COLORS.orange,
    opacity: 0.7,
  },
  dotBlue: {
    position: "absolute",
    top: 150,
    right: 95,
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: "#8CB6FF",
    opacity: 0.8,
  },
  crossBlue: {
    position: "absolute",
    top: 130,
    right: 70,
    width: 14,
    height: 14,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: "#B6C9F9",
    transform: [{ rotate: "45deg" }],
    opacity: 0.6,
  },

  bottomWave1: {
    position: "absolute",
    bottom: -210,
    left: -120,
    width: 760,
    height: 320,
    borderRadius: 9999,
    backgroundColor: COLORS.blue2,
    transform: [{ rotate: "-2deg" }],
  },
  bottomWave2: {
    position: "absolute",
    bottom: -230,
    left: -10,
    width: 820,
    height: 320,
    borderRadius: 9999,
    backgroundColor: COLORS.blue,
    opacity: 0.9,
    transform: [{ rotate: "-1deg" }],
  },
  bottomWave3: {
    position: "absolute",
    bottom: -250,
    right: -60,
    width: 520,
    height: 240,
    borderRadius: 9999,
    backgroundColor: COLORS.orange,
    opacity: 0.45,
  },

  card: {
    width: "90%",
    maxWidth: 420,
    backgroundColor: COLORS.card,
    borderRadius: 18,
    padding: 24,
    borderWidth: 1,
    borderColor: COLORS.border,
    zIndex: 1,
    shadowColor: "#000",
    shadowOpacity: 0.14,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  logo: {
    width: "100%",
    height: 80,
    resizeMode: "contain",
    alignSelf: "center",
    marginBottom: 8,
  },
  title: {
    fontSize: 26,
    fontWeight: "800",
    color: COLORS.blue2,
    marginBottom: 6,
    textAlign: "center",
  },
  subtitle: {
    fontSize: 14,
    color: COLORS.muted,
    marginBottom: 18,
    textAlign: "center",
  },
  label: {
    fontSize: 13,
    fontWeight: "700",
    color: COLORS.text,
    marginBottom: 6,
  },
  input: {
    height: 46,
    borderWidth: 1,
    borderColor: "#D8E3FB",
    borderRadius: 12,
    paddingHorizontal: 14,
    color: COLORS.text,
    backgroundColor: "#EEF4FF",
    marginBottom: 12,
  },
  button: {
    height: 50,
    borderRadius: 12,
    backgroundColor: COLORS.blue2,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 6,
    shadowColor: "#0B2C5D",
    shadowOpacity: 0.2,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
  },
  buttonText: { color: COLORS.white, fontWeight: "800", fontSize: 15 },
  linkBtn: { marginTop: 10, alignItems: "center" },
  linkBtnText: { color: COLORS.blue2, fontWeight: "800" },
  resetBox: {
    marginTop: 12,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.grayBorder,
    backgroundColor: "#F8FAFF",
  },
  resetTitle: { fontWeight: "800", color: COLORS.text, marginBottom: 10 },
  secondaryBtn: {
    height: 40,
    borderRadius: 10,
    backgroundColor: "#EEF3FF",
    borderWidth: 1,
    borderColor: "#D9E5FF",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  secondaryBtnText: { color: COLORS.blue2, fontWeight: "800" },
  resetMsg: { color: COLORS.muted, fontWeight: "700", marginTop: 6 },
  footer: {
    marginTop: 16,
    textAlign: "center",
    color: COLORS.muted,
    fontSize: 12,
    fontWeight: "700",
  },
});

export default styles;
